// Archetype catalogue. Each entry owns its own palette so the whole card
// (donut, mood bar, glow, type) recolors when the archetype changes.

export const ARCHETYPES = {
  wanderer: {
    id: 'wanderer',
    name: 'The Wanderer',
    emoji: '🧭',
    descriptor: ['You never let a genre hold you down.', 'Every playlist is a passport stamp.'],
    shadow: 'Allergic to commitment — you ghost a song the second it gets comfortable.',
    spirit: 'Björk',
    palette: { base: '#0b1410', glow: '#2fd6a6', accent: '#c6ff4a', ink: '#eafff4' },
    wheel: ['#2fd6a6', '#c6ff4a', '#5be0c8', '#a0f08a', '#1f9e7a', '#dfff9a'],
  },
  ritualist: {
    id: 'ritualist',
    name: 'The Ritualist',
    emoji: '🕯️',
    descriptor: ['The same songs, on purpose, forever.', 'Repetition is your love language.'],
    shadow: 'Your "discover weekly" is a graveyard you never visit.',
    spirit: 'Bon Iver',
    palette: { base: '#150f0a', glow: '#f5a742', accent: '#f5c542', ink: '#fff3e0' },
    wheel: ['#f5a742', '#f5c542', '#d98324', '#ffd97a', '#b8651a', '#ffe7b0'],
  },
  hedonist: {
    id: 'hedonist',
    name: 'The Hedonist',
    emoji: '🍒',
    descriptor: ['Life is a dancefloor and you booked the whole night.', 'If it doesn’t move you, it’s deleted.'],
    shadow: 'You confuse a serotonin spike for a personality.',
    spirit: 'Dua Lipa',
    palette: { base: '#19090f', glow: '#ff3d77', accent: '#ffb13d', ink: '#ffe5ee' },
    wheel: ['#ff3d77', '#ffb13d', '#ff6a9e', '#ffd06a', '#d61f5a', '#ffc1d6'],
  },
  introspect: {
    id: 'introspect',
    name: 'The Introspect',
    emoji: '🌫️',
    descriptor: ['You listen the way other people pray.', 'Volume low, feelings catastrophic.'],
    shadow: 'You romanticize sadness until it pays rent in your chest.',
    spirit: 'Phoebe Bridgers',
    palette: { base: '#0a0e16', glow: '#7aa5ff', accent: '#b9c9ff', ink: '#e8eeff' },
    wheel: ['#7aa5ff', '#b9c9ff', '#5d86e0', '#9fb6f5', '#3f63bf', '#d4dfff'],
  },
  architect: {
    id: 'architect',
    name: 'The Architect',
    emoji: '📐',
    descriptor: ['You hear blueprints where others hear noise.', 'Structure is the highest form of beauty.'],
    shadow: 'You’d rather analyze the bridge than feel the song.',
    spirit: 'Aphex Twin',
    palette: { base: '#0a1212', glow: '#34d3d3', accent: '#9affff', ink: '#e2ffff' },
    wheel: ['#34d3d3', '#9affff', '#1f9e9e', '#6fe6e6', '#127777', '#c4ffff'],
  },
  anarchist: {
    id: 'anarchist',
    name: 'The Anarchist',
    emoji: '⚡',
    descriptor: ['Loud, fast, and allergic to the rules.', 'You treat genre conventions as a dare.'],
    shadow: 'Chaos is a comfort blanket you refuse to wash.',
    spirit: 'Death Grips',
    palette: { base: '#160808', glow: '#ff4530', accent: '#ff8a3d', ink: '#ffe2dc' },
    wheel: ['#ff4530', '#ff8a3d', '#e02818', '#ffae6a', '#a81708', '#ffc9b0'],
  },
  romantic: {
    id: 'romantic',
    name: 'The Romantic',
    emoji: '🌹',
    descriptor: ['Every song is a love letter you didn’t send.', 'Warmth over everything, always.'],
    shadow: 'You score your own life and forget to live the scene.',
    spirit: 'Frank Ocean',
    palette: { base: '#160a10', glow: '#ff79b0', accent: '#ffd0a0', ink: '#ffe9f2' },
    wheel: ['#ff79b0', '#ffd0a0', '#e85a93', '#ffbf8a', '#c43d72', '#ffd9e6'],
  },
  zeitgeist: {
    id: 'zeitgeist',
    name: 'The Zeitgeist',
    emoji: '📈',
    descriptor: ['You’re early on everything, loyal to nothing.', 'The chart is your compass.'],
    shadow: 'Your taste expires faster than the trend that fed it.',
    spirit: 'Taylor Swift',
    palette: { base: '#0e0a16', glow: '#a06bff', accent: '#ff6ad5', ink: '#f1e8ff' },
    wheel: ['#a06bff', '#ff6ad5', '#8048e0', '#d98aff', '#5e2eb8', '#f0c4ff'],
  },
  ghost: {
    id: 'ghost',
    name: 'The Ghost',
    emoji: '👻',
    descriptor: ['You haunt the parts of streaming nobody else reaches.', 'No lyrics, no witnesses.'],
    shadow: 'You hide inside obscurity so no one can judge the taste.',
    spirit: 'Tim Hecker',
    palette: { base: '#0c0e0d', glow: '#9fb3a8', accent: '#cfd8d2', ink: '#eef2f0' },
    wheel: ['#9fb3a8', '#cfd8d2', '#7d9389', '#bcc8c1', '#5e7066', '#e2e8e4'],
  },
  catalyst: {
    id: 'catalyst',
    name: 'The Catalyst',
    emoji: '🜔',
    descriptor: ['You don’t have a lane — you have a spectrum.', 'Balance, but make it electric.'],
    shadow: 'So open-minded your brain occasionally falls out.',
    spirit: 'Gorillaz',
    palette: { base: '#120c08', glow: '#ffd23d', accent: '#3bdc8f', ink: '#fff6df' },
    wheel: ['#ffd23d', '#3bdc8f', '#ff7a3d', '#5ad2ff', '#c64fff', '#ff5a8a'],
  },
}

export const ARCHETYPE_LIST = Object.values(ARCHETYPES)
